<a href="https://colab.research.google.com/github/rahiakela/deep-learning-research-and-practice/blob/main/inside-deep-learing/01-foundational-methods/01-learning-mechanics/01_tensor_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##The world as tensors

In [1]:
import torch

import numpy as np
import pandas as pd

import timeit

from tqdm.autonotebook import tqdm
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# create pytorch tensor
torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1, 2, 3, 4])
torch_metrix = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]                         
])
torch_3d = torch.tensor([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ],
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]                  
])

In [3]:
print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_metrix.shape)
print(torch_3d.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 4])


In [4]:
# create numpy tensor
x_np = np.random.random((4, 4))
print(x_np)

[[0.61538791 0.20573358 0.31200794 0.71514441]
 [0.38817292 0.64873112 0.67365101 0.01635404]
 [0.43452298 0.77886447 0.38905111 0.2972679 ]
 [0.94936055 0.71895291 0.50415977 0.75078583]]


In [5]:
# convert numpy to pytorch tensor
x_pt = torch.tensor(x_np)
print(x_pt)

tensor([[0.6154, 0.2057, 0.3120, 0.7151],
        [0.3882, 0.6487, 0.6737, 0.0164],
        [0.4345, 0.7789, 0.3891, 0.2973],
        [0.9494, 0.7190, 0.5042, 0.7508]], dtype=torch.float64)


In [6]:
# check data type
print(x_np.dtype, x_pt.dtype)

float64 torch.float64


In [7]:
# Let’s force them to be 32-bit floats
x_np = np.asarray(x_np, dtype=np.float32)
x_pt = torch.tensor(x_np, dtype=torch.float32)

print(x_np.dtype, x_pt.dtype)

float32 torch.float32


In [8]:
# let's find every value greater than 0.5 in a tensor
b_np = (x_np > 0.5)
print(b_np)
print(b_np.dtype)

[[ True False False  True]
 [False  True  True False]
 [False  True False False]
 [ True  True  True  True]]
bool


In [9]:
b_pt = (x_pt > 0.5)
print(b_pt)
print(b_pt.dtype)

tensor([[ True, False, False,  True],
        [False,  True,  True, False],
        [False,  True, False, False],
        [ True,  True,  True,  True]])
torch.bool


In [10]:
# let's sum tensor value
np.sum(x_np)

8.398149

In [11]:
torch.sum(x_pt)

tensor(8.3981)

In [12]:
# let's transpose tensor
np.transpose(x_np)

array([[0.6153879 , 0.38817292, 0.434523  , 0.94936055],
       [0.20573358, 0.6487311 , 0.77886444, 0.7189529 ],
       [0.31200793, 0.67365104, 0.3890511 , 0.50415975],
       [0.7151444 , 0.01635404, 0.2972679 , 0.7507858 ]], dtype=float32)

In [13]:
torch.transpose(x_pt, 0, 1)

tensor([[0.6154, 0.3882, 0.4345, 0.9494],
        [0.2057, 0.6487, 0.7789, 0.7190],
        [0.3120, 0.6737, 0.3891, 0.5042],
        [0.7151, 0.0164, 0.2973, 0.7508]])

In [14]:
# let's transpose dimensions wise
print(torch_3d.shape)

torch.Size([2, 2, 4])


In [15]:
# let's transpose the first and third dimensions, we get a shape of (4, 2, 2)
print(torch.transpose(torch_3d, 0, 2).shape)

torch.Size([4, 2, 2])


##PyTorch GPU acceleration

In [16]:
x = torch.rand(2 ** 11, 2 ** 11)
time_cpu = timeit.timeit("x@x", globals=globals(), number=100)

In [17]:
time_cpu

30.743872181

In [18]:
# let's check GPU is avaialble
print(f"Is CUDA available? : {torch.cuda.is_available()}")

Is CUDA available? : True


In [19]:
device = torch.device("cuda")

In [20]:
# now, let's move x to GPU device
x = x.to(device)
time_gpu = timeit.timeit("x@x", globals=globals(), number=100)
time_gpu

0.02783245200004103

In [23]:
# let's try to make the matrix smaller and see how that impacts the speedup
y = torch.rand(2 ** 4, 2 ** 4)
time_cpu = timeit.timeit("y@y", globals=globals(), number=100)
time_cpu

0.0007066449999229008

In [24]:
y = y.to(device)
time_gpu = timeit.timeit("y@y", globals=globals(), number=100)
time_gpu

0.0020799279999437204

Be aware that this only works if every object involved is on the same device

In [25]:
x = torch.rand(128, 128).to(device)
y = torch.rand(128, 128)

x * y

RuntimeError: ignored

In [26]:
# let's change the operation order
y * x

RuntimeError: ignored

The other thing to be aware of is how to convert PyTorch data back to the CPU.

In [27]:
# convert a tensor back to NumPy array
x.numpy()

TypeError: ignored

In [28]:
# we need to move tensor first to cpu
x.cpu().numpy()

array([[0.47301322, 0.7353228 , 0.16693443, ..., 0.5516606 , 0.7507018 ,
        0.84979534],
       [0.7395101 , 0.6326684 , 0.889756  , ..., 0.3624186 , 0.2215904 ,
        0.7190404 ],
       [0.92088807, 0.5501011 , 0.9038619 , ..., 0.8990911 , 0.9849934 ,
        0.24517703],
       ...,
       [0.5127104 , 0.29696852, 0.37228227, ..., 0.11635119, 0.4324844 ,
        0.51874995],
       [0.69576275, 0.97957474, 0.42679274, ..., 0.0453108 , 0.8387493 ,
        0.84938604],
       [0.35797238, 0.8131727 , 0.6302763 , ..., 0.5749145 , 0.16673273,
        0.5605307 ]], dtype=float32)

Let's define a function, which goes recursively
through the common `Python` and `PyTorch` containers and moves every object found onto the specified device.

In [29]:
def move_to(obj, device):
  """
  obj: the python object to move to a device, or to move its contents to a device
  device: the compute device to move objects to
  """
  if isinstance(obj, list):
    return [move_to(x, device) for x in obj]
  elif isinstance(obj, tuple):
    return (move_to(list(obj), device))
  elif isinstance(obj, set):
    return set(move_to(list(obj), device))
  elif isinstance(obj, dict):
    to_ret = dict()
    for key, value in obj.items():
      to_ret[move_to(key, device)] = move_to(value, device)
    return to_ret
  elif hasattr(obj, "to"):
    return obj.to(device)
  else:
    return obj

In [30]:
some_tensors = [torch.tensor(1), torch.tensor(2)]
print(some_tensors)

# let's move to GPU
print(move_to(some_tensors, device))

[tensor(1), tensor(2)]
[tensor(1, device='cuda:0'), tensor(2, device='cuda:0')]


In [31]:
# let's move to CPU
print(move_to(some_tensors, "cpu"))

[tensor(1), tensor(2)]
