<a href="https://colab.research.google.com/github/rahiakela/deep-learning-research-and-practice/blob/main/inside-deep-learing/01-foundational-methods/02_tensor_reshape_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Setup

In [ ]:
from tqdm.autonotebook import tqdm

import numpy as np
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt

import pandas as pd

import time

In [ ]:
import torch

##Tensor reshape fundamental

What is special about reshape is that it
lets us specify all but one of the dimensions, and it automatically puts the leftovers
into the unspecified dimension. 

This leftover dimension is denoted with –1.

In [ ]:
x_np = np.random.random((6, 1))
a = torch.tensor(x_np)
print(a)
print(a.shape)
print(a.reshape(6))
print(a.reshape(6).shape)

tensor([[0.5445],
        [0.0058],
        [0.3246],
        [0.3665],
        [0.3962],
        [0.6955]], dtype=torch.float64)
torch.Size([6, 1])
tensor([0.5445, 0.0058, 0.3246, 0.3665, 0.3962, 0.6955], dtype=torch.float64)
torch.Size([6])


In [ ]:
x_np = np.random.random((6, 1))
a = torch.tensor(x_np)
print(a)
print(a.shape)
print(a.reshape(-1))
print(a.reshape(-1).shape)

tensor([[0.8078],
        [0.7623],
        [0.7978],
        [0.4356],
        [0.8178],
        [0.1202]], dtype=torch.float64)
torch.Size([6, 1])
tensor([0.8078, 0.7623, 0.7978, 0.4356, 0.8178, 0.1202], dtype=torch.float64)
torch.Size([6])


If you know the exact size, you can
specify it; or if you don’t know the size for one axis, you can use –1 to indicate a leftover spot.

In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(3, 2))
print(b.reshape(3, 2).shape)

tensor([[0.5670, 0.7384],
        [0.8785, 0.4041],
        [0.3270, 0.6676]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[0.5670, 0.7384],
        [0.8785, 0.4041],
        [0.3270, 0.6676]], dtype=torch.float64)
torch.Size([3, 2])


In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(-1, 2))
print(b.reshape(-1, 2).shape)

tensor([[0.9994, 0.0482],
        [0.9772, 0.4069],
        [0.8708, 0.7824]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[0.9994, 0.0482],
        [0.9772, 0.4069],
        [0.8708, 0.7824]], dtype=torch.float64)
torch.Size([3, 2])


In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(3, 2))
print(b.reshape(3, 2).shape)

tensor([[0.2157, 0.6589],
        [0.3939, 0.6512],
        [0.1066, 0.6578]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[0.2157, 0.6589],
        [0.3939, 0.6512],
        [0.1066, 0.6578]], dtype=torch.float64)
torch.Size([3, 2])


In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(-1, 2))
print(b.reshape(-1, 2).shape)

tensor([[0.8689, 0.5706],
        [0.0304, 0.9309],
        [0.6895, 0.6765]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[0.8689, 0.5706],
        [0.0304, 0.9309],
        [0.6895, 0.6765]], dtype=torch.float64)
torch.Size([3, 2])


In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(3, -1))
print(b.reshape(3, -1).shape)

tensor([[0.6926, 0.8381],
        [0.9446, 0.6832],
        [0.4972, 0.6178]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[0.6926, 0.8381],
        [0.9446, 0.6832],
        [0.4972, 0.6178]], dtype=torch.float64)
torch.Size([3, 2])


In [ ]:
x_np = np.random.random((2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(2, 3))
print(b.reshape(2, 3).shape)

tensor([[0.9699, 0.0939, 0.6726],
        [0.4438, 0.8681, 0.1771]], dtype=torch.float64)
torch.Size([2, 3])
tensor([[0.9699, 0.0939, 0.6726],
        [0.4438, 0.8681, 0.1771]], dtype=torch.float64)
torch.Size([2, 3])


In [ ]:
x_np = np.random.random((2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(-1, 3))
print(b.reshape(-1, 3).shape)

tensor([[0.1397, 0.0300, 0.3079],
        [0.7047, 0.2019, 0.6734]], dtype=torch.float64)
torch.Size([2, 3])
tensor([[0.1397, 0.0300, 0.3079],
        [0.7047, 0.2019, 0.6734]], dtype=torch.float64)
torch.Size([2, 3])


In [ ]:
x_np = np.random.random((2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(2, -1))
print(b.reshape(2, -1).shape)

tensor([[0.6391, 0.8679, 0.4547],
        [0.5156, 0.4888, 0.6669]], dtype=torch.float64)
torch.Size([2, 3])
tensor([[0.6391, 0.8679, 0.4547],
        [0.5156, 0.4888, 0.6669]], dtype=torch.float64)
torch.Size([2, 3])


In [ ]:
x_np = np.random.random((1, 2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(1, 3, 2))
print(b.reshape(1, 3, 2).shape)

tensor([[[0.2285, 0.9963, 0.9748],
         [0.6503, 0.1995, 0.6802]]], dtype=torch.float64)
torch.Size([1, 2, 3])
tensor([[[0.2285, 0.9963],
         [0.9748, 0.6503],
         [0.1995, 0.6802]]], dtype=torch.float64)
torch.Size([1, 3, 2])


In [ ]:
x_np = np.random.random((1, 2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(-1, 3, 2))
print(b.reshape(-1, 3, 2).shape)

tensor([[[0.0722, 0.0307, 0.2577],
         [0.4626, 0.8683, 0.7272]]], dtype=torch.float64)
torch.Size([1, 2, 3])
tensor([[[0.0722, 0.0307],
         [0.2577, 0.4626],
         [0.8683, 0.7272]]], dtype=torch.float64)
torch.Size([1, 3, 2])


In [ ]:
x_np = np.random.random((1, 2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(1, -1, 2))
print(b.reshape(1, -1, 2).shape)

tensor([[[0.7427, 0.4255, 0.3459],
         [0.3710, 0.9876, 0.0401]]], dtype=torch.float64)
torch.Size([1, 2, 3])
tensor([[[0.7427, 0.4255],
         [0.3459, 0.3710],
         [0.9876, 0.0401]]], dtype=torch.float64)
torch.Size([1, 3, 2])


In [ ]:
x_np = np.random.random((1, 2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(1, 3, -1))
print(b.reshape(1, 3, -1).shape)

tensor([[[0.8670, 0.5787, 0.4386],
         [0.7253, 0.4867, 0.8734]]], dtype=torch.float64)
torch.Size([1, 2, 3])
tensor([[[0.8670, 0.5787],
         [0.4386, 0.7253],
         [0.4867, 0.8734]]], dtype=torch.float64)
torch.Size([1, 3, 2])


If you have a total of N items in your tensor, you can reshape it into any
new number of dimensions as long as the final number of items adds to N.

For example, we can turn the `N = 6` values into a tensor
with five dimensions by doing `(3, 1, 1, 2, 1)` because `3 x 1 x 1 x 2 x 1 = 6`.

In [ ]:
x_np = np.random.random((2, 3))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(3, 1, 1, 2, 1))
print(b.reshape(3, 1, 1, 2, 1).shape)

tensor([[0.3886, 0.4487, 0.2375],
        [0.3733, 0.2273, 0.0732]], dtype=torch.float64)
torch.Size([2, 3])
tensor([[[[[0.3886],
           [0.4487]]]],



        [[[[0.2375],
           [0.3733]]]],



        [[[[0.2273],
           [0.0732]]]]], dtype=torch.float64)
torch.Size([3, 1, 1, 2, 1])


In [ ]:
x_np = np.random.random((3, 2))
b = torch.tensor(x_np)
print(b)
print(b.shape)
print(b.reshape(3, 1, 1, 2, 1))
print(b.reshape(3, 1, 1, 2, 1).shape)

tensor([[0.6034, 0.6682],
        [0.6195, 0.4635],
        [0.3798, 0.8633]], dtype=torch.float64)
torch.Size([3, 2])
tensor([[[[[0.6034],
           [0.6682]]]],



        [[[[0.6195],
           [0.4635]]]],



        [[[[0.3798],
           [0.8633]]]]], dtype=torch.float64)
torch.Size([3, 1, 1, 2, 1])


The `view` function has the same kind of behavior.

Because `view` uses less memory and can be faster but can throw errors if used inappropriately.