<a href="https://colab.research.google.com/github/rahiakela/deep-learning-research-and-practice/blob/main/inside-deep-learing/01-foundational-methods/01-learning-mechanics/01_tensor_world.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##The world as tensors

In [2]:
import torch

import numpy as np
import pandas as pd

from tqdm.autonotebook import tqdm
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
# create pytorch tensor
torch_scalar = torch.tensor(3.14)
torch_vector = torch.tensor([1, 2, 3, 4])
torch_metrix = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6]                         
])
torch_3d = torch.tensor([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8]
    ],
    [
      [9, 10, 11, 12],
      [13, 14, 15, 16]
    ]                  
])

In [4]:
print(torch_scalar.shape)
print(torch_vector.shape)
print(torch_metrix.shape)
print(torch_3d.shape)

torch.Size([])
torch.Size([4])
torch.Size([3, 2])
torch.Size([2, 2, 4])


In [5]:
# create numpy tensor
x_np = np.random.random((4, 4))
print(x_np)

[[0.553091   0.06504068 0.7442383  0.50332409]
 [0.33766211 0.52568117 0.30361864 0.84786368]
 [0.31177298 0.32954231 0.31271585 0.47616938]
 [0.69873185 0.0923461  0.30799688 0.57967637]]


In [6]:
# convert numpy to pytorch tensor
x_pt = torch.tensor(x_np)
print(x_pt)

tensor([[0.5531, 0.0650, 0.7442, 0.5033],
        [0.3377, 0.5257, 0.3036, 0.8479],
        [0.3118, 0.3295, 0.3127, 0.4762],
        [0.6987, 0.0923, 0.3080, 0.5797]], dtype=torch.float64)


In [7]:
# check data type
print(x_np.dtype, x_pt.dtype)

float64 torch.float64


In [8]:
# Let’s force them to be 32-bit floats
x_np = np.asarray(x_np, dtype=np.float32)
x_pt = torch.tensor(x_np, dtype=torch.float32)

print(x_np.dtype, x_pt.dtype)

float32 torch.float32


In [9]:
# let's find every value greater than 0.5 in a tensor
b_np = (x_np > 0.5)
print(b_np)
print(b_np.dtype)

[[ True False  True  True]
 [False  True False  True]
 [False False False False]
 [ True False False  True]]
bool


In [10]:
b_pt = (x_pt > 0.5)
print(b_pt)
print(b_pt.dtype)

tensor([[ True, False,  True,  True],
        [False,  True, False,  True],
        [False, False, False, False],
        [ True, False, False,  True]])
torch.bool


In [11]:
# let's sum tensor value
np.sum(x_np)

6.9894714

In [12]:
torch.sum(x_pt)

tensor(6.9895)

In [13]:
# let's transpose tensor
np.transpose(x_np)

array([[0.553091  , 0.3376621 , 0.31177297, 0.69873184],
       [0.06504069, 0.5256812 , 0.3295423 , 0.09234609],
       [0.7442383 , 0.30361864, 0.31271586, 0.3079969 ],
       [0.5033241 , 0.8478637 , 0.47616938, 0.5796764 ]], dtype=float32)

In [14]:
torch.transpose(x_pt, 0, 1)

tensor([[0.5531, 0.3377, 0.3118, 0.6987],
        [0.0650, 0.5257, 0.3295, 0.0923],
        [0.7442, 0.3036, 0.3127, 0.3080],
        [0.5033, 0.8479, 0.4762, 0.5797]])

In [15]:
# let's transpose dimensions wise
print(torch_3d.shape)

torch.Size([2, 2, 4])


In [16]:
# let's transpose the first and third dimensions, we get a shape of (4, 2, 2)
print(torch.transpose(torch_3d, 0, 2).shape)

torch.Size([4, 2, 2])
